### ISSUE TITLE
immutable Paulis/Cliffords

### ISSUE THREAD

**Issue by blakejohnson** [BBN-Q/Cliffords.jl#4]
It seems like FixedSizeArrays.jl is basically deprecated and we should use https://github.com/JuliaArrays/StaticArrays.jl from now on. I'll take a crack at converting the immutable-arrays branch to use that.

**Comment by blakejohnson** [comment]
So, initial bad news on the performance of the immutable version. Using this benchmarking script:
```julia
using Cliffords, BenchmarkTools

rand_c1seq = rand(1:24, 1_000)
benchc1(seq) = reduce(*, localclifford(n) for n in seq)

# create some of C2
C2 = Clifford[]
for _ in 1:100
    c = kron(localclifford(rand(1:24)), localclifford(rand(1:24)))
    if rand() > 0.5
        push!(C2, c)
    else
        push!(C2, c * CNOT * c)
    end
end

rand_c2seq = rand(1:100, 1_000)
benchc2(seq) = reduce(*, C2[n] for n in seq)

println("C1 benchmarking:\n")
r1 = @benchmark benchc1(rand_c1seq)
print(r1)

println("C2 benchmarking:\n")
r2 = @benchmark benchc2(rand_c2seq)
print(r2)
```

I get the following performance:

Test | master | immutable-arrays
-----|--------|-----------------
C1 | 86ms   | 139ms
C2 | 190ms | 749ms

I'm rather surprised, so I will spend a little time profiling to see what is going on.

**Comment by blakejohnson** [comment]
Ok, I found some major performance traps and fixed them. On 98eb752 (immutable arrays) I now see:

Test | immutable-arrays
-----|------------------
C1 | 80 ms
C2 | 217 ms

I expect I can find more low hanging fruit.

**Comment by blakejohnson** [comment]
Note that everything I changed so far is related to `Pauli` operations, as opposed to `Clifford`s.

**Comment by blakejohnson** [comment]
Oh, another benefit is that the immutable-arrays branch uses over 10x less memory than master to run these tests.

**Comment by blakejohnson** [comment]
Oh yeah... there was more low hanging fruit. New numbers on d3af44f

Test | d3af44f
-----|---------
C1    |  8.5ms
C2    |  35ms

**Comment by blakejohnson** [comment]
So, the immutable-arrays branch is good enough now that I merged it into master. However, there is still room to improve, as it looks like our `Clifford * Clifford` multiplication is still 40x slower than multiplying 4x4 complex matrices.

**Comment by marcusps** [comment]
Given the representation we use (dictionaries of generators), this may be hard to beat for small matrices, as matrix multiplication is heavily optimized.  If we look at more and more qubits we might be able to see speed gain over the complex matrix representation (since that will slow down exponentially).

**Comment by blakejohnson** [comment]
Found another factor of 2 in e7cae0e. I think there is more room for optimization even with our current representation. I think with a little more work we can get within 10x of plain matrix multiplication.

**Comment by blakejohnson** [comment]
Recording new numbers:

Test | e7cae0e
-----|---------
C1    |  5.0ms
C2    |  15.8ms

At this point, especially for C1 multiplication, we are mostly limited by our representation. We actually spend 50% of the benchmark time in initializing empty `Dict{Pauli{1},Pauli{1}}`'s, and if you look a level deeper, it is creating the array which backs the `Dict`. So, unless there is some magic way to avoid that overhead, this is nearly as far as we can take it.
